### PR TITLE
chore: update docs for Cloud Connect 3.3.0

### PR DESCRIPTION
**Pull request by smbea**

### CODE REVIEW

**Comment by barmac** [comment]
I think this part will also need to be updated: https://github.com/camunda/camunda-docs-cawemo/blob/update-docs-cloud-connect-3.3.0/content/technical-guide/integrations/modeler.md

**Comment by smbea** [comment]
> I think this part will also need to be updated: https://github.com/camunda/camunda-docs-cawemo/blob/update-docs-cloud-connect-3.3.0/content/technical-guide/integrations/modeler.md

Working on this now.

The current `3.x` would be `3.0, 3.1, 3.2`. What is the proper way to represent this here?

**Comment by barmac** [comment]
I think `3.0-3.2` would make sense. WDYT @CatalinaMoisuc?

**Comment by CatalinaMoisuc** [comment]
> I think `3.0-3.2` would make sense. WDYT @CatalinaMoisuc?

Yes, we do the same for Engine. See:

https://github.com/camunda/camunda-docs-cawemo/blob/update-docs-cloud-connect-3.3.0/content/technical-guide/integrations/engine.md#compatibility

**Comment by smbea** [comment]
Ready for review

**Review by barmac — APPROVED** [review]

**Review by CatalinaMoisuc — APPROVED** [review]

**Pull request merged**
