### PR TITLE
Change to the new artifactory domain

### PR DESCRIPTION
**Pull request by chaima-mnsr**
Related to INFRA-3183

### CODE REVIEW

**Review by Langleu — APPROVED** [review]

**Comment by chaima-mnsr** [comment]
Hey @wollefitz, Yes it is a known issue that we will fix once the customers know about the new URL, this problem happens only when connecting with SSO. is this the way the customers connect ?

**Comment by wollefitz** [comment]
> is this the way the customers connect ?

Honestly: No idea since artifactory is owned by Infra and not by us. But this means that with the current state I'm not able to test this (although everything looks fine by just looking at the changes).

**Comment by chaima-mnsr** [comment]
@wollefitz I double-checked and customers use LDAP to authenticate so this should not be a problem for them.

**Comment by wollefitz** [comment]
> @wollefitz I double-checked and customers use LDAP to authenticate so this should not be a problem for them.

In that case I can not really provide any additional value to this PR - as mentioned above, the changes look fine to me but I can't test them.

**Comment by chaima-mnsr** [comment]
All good, we can merge the PR, we are pretty confident about the change

**Pull request merged**
