### PR TITLE
chore(theme): update docs theme

### PR DESCRIPTION
**Pull request by akeller**
Related to [CAM-14373](https://jira.camunda.com/browse/CAM-14373).

### CODE REVIEW

**Review by CatalinaMoisuc — CHANGES_REQUESTED** [review]
@akeller I managed to find some places that might need rephrasing to reflect version 7, but it is not 100% clear to me how they should be renamed so I will leave it for you to either contribute or answer the questions.

Here I curated a list of the files/lines of code that contain "Platform" and were untouched:

How do we call Engine, should it be Camunda Platform 7 Engine?
https://github.com/camunda/camunda-docs-cawemo/blob/727623e3931940b00ff04bd19cfd7811cd151876/content/technical-guide/integrations/_index.md?plain=1#L9

How should it be phrased here: “Camunda Enterprise Platform”?
https://github.com/camunda/camunda-docs-cawemo/blob/727623e3931940b00ff04bd19cfd7811cd151876/content/technical-guide/installation/_index.md?plain=1#L31
Similar cases in this file
https://github.com/camunda/camunda-docs-cawemo/blob/CAM-14373-latest/content/technical-guide/integrations/engine.md
And similar in this file:
https://github.com/camunda/camunda-docs-cawemo/blob/CAM-14373-latest/content/technical-guide/third-party-libraries/engine-plugin-third-party-libraries.md
Same here:
https://github.com/camunda/camunda-docs-cawemo/blob/727623e3931940b00ff04bd19cfd7811cd151876/content/user-guide/milestones.md?plain=1#L28
And here:
https://github.com/camunda/camunda-docs-cawemo/blob/727623e3931940b00ff04bd19cfd7811cd151876/content/user-guide/settings.md?plain=1#L20
One more location in the Themes:
https://github.com/camunda/camunda-docs-cawemo/blob/727623e3931940b00ff04bd19cfd7811cd151876/themes/camunda/layouts/partials/footer.html#L11



And how do we call Camunda Platform Run? Should there be a 7 also there?
https://github.com/camunda/camunda-docs-cawemo/blob/727623e3931940b00ff04bd19cfd7811cd151876/themes/camunda/layouts/shortcodes/ee-download.html#L55

**Comment by akeller** [comment]
@CatalinaMoisuc I don't have a good answer to these questions so I'll need to get back to you on these. I do think this sits outside the scope of these PRs. I'll check in with our product managers and product marketing managers this week to see if I can get a better understanding of naming in the context you've provided.

**Review by CatalinaMoisuc — APPROVED** [review]

**Comment by akeller** [comment]
@CatalinaMoisuc do I merge these? Or does someone on your team take care of merging?

**Comment by CatalinaMoisuc** [comment]
> @CatalinaMoisuc do I merge these? Or does someone on your team take care of merging?

I was unsure and thus waiting for you to decide. I just merged all 3 PRs. Thanks @akeller. 😸

**Pull request merged**
