### PR TITLE
chore(theme): updates docs theme

### PR DESCRIPTION
**Pull request by akeller**
Related to [CAM-14373](https://jira.camunda.com/browse/CAM-14373).

Please let me know if you need a separate JIRA ticket for this work or would like this update applied to other branches.

### CODE REVIEW

**Comment by CatalinaMoisuc** [comment]
@akeller What are the requirements? Should this change be reflected in all previous released versions or just the next one?

For some context:
In the dropdown (see screenshot below):
* the `master` branch is the equivalent of `develop`
* the `latest` branch is the equivalent of `1.9` (the latest version released)

Screenshot 2022-03-08 at 09 44 09

**Comment by akeller** [comment]
@CatalinaMoisuc - how many versions are currently supported? We should cover those. So for instance, with Optimize we covered `master`, `latest`, and `3.3`-`3.7`. My goal with this is to at least cover the current version, future version, and maybe some of the currently supported versions depending on how much effort that would take.

I'm happy to create more PRs, just let me know which branch names. Sounds like I should also create one for `latest`.

**Review by CatalinaMoisuc — CHANGES_REQUESTED** [review]
See comments about the actual changes in the other PR: https://github.com/camunda/camunda-docs-cawemo/pull/188#pullrequestreview-905383085.

**Comment by CatalinaMoisuc** [comment]
See: https://github.com/camunda/camunda-docs-cawemo/pull/188#issuecomment-1067007318.

**Review by CatalinaMoisuc — APPROVED** [review]

**Pull request merged**
